---
script: rake travis
before_script:
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
language: ruby
notifications:
  email:
  - evan@fallingsnow.net
  - drbrain@segment7.net
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
